// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: device.sql

package db

import (
	"context"
)

const saveDevice = `-- name: SaveDevice :exec
INSERT INTO devices (
    device_id,
    device_token,
    user_id,
    last_used_at
) VALUES (
    $1, $2, $3, current_timestamp
)
ON CONFLICT (device_id)
    DO UPDATE SET
    device_token = EXCLUDED.device_token,
    last_used_at = current_timestamp
`

type SaveDeviceParams struct {
	DeviceID    string `json:"device_id"`
	DeviceToken string `json:"device_token"`
	UserID      string `json:"user_id"`
}

func (q *Queries) SaveDevice(ctx context.Context, arg SaveDeviceParams) error {
	_, err := q.db.Exec(ctx, saveDevice, arg.DeviceID, arg.DeviceToken, arg.UserID)
	return err
}
