// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: experience.sql

package db

import (
	"context"
)

const saveExperience = `-- name: SaveExperience :one
INSERT INTO experiences (
    user_id,
    practice_area,
    practice_location,
    experience
) VALUES (
    $1, $2, $3, $4
) RETURNING experience_id, user_id, practice_area, practice_location, experience
`

type SaveExperienceParams struct {
	UserID           string `json:"user_id"`
	PracticeArea     string `json:"practice_area"`
	PracticeLocation string `json:"practice_location"`
	Experience       string `json:"experience"`
}

func (q *Queries) SaveExperience(ctx context.Context, arg SaveExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, saveExperience,
		arg.UserID,
		arg.PracticeArea,
		arg.PracticeLocation,
		arg.Experience,
	)
	var i Experience
	err := row.Scan(
		&i.ExperienceID,
		&i.UserID,
		&i.PracticeArea,
		&i.PracticeLocation,
		&i.Experience,
	)
	return i, err
}
