// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: firm.sql

package db

import (
	"context"
)

const addFirm = `-- name: AddFirm :one
INSERT INTO firms (
    name,
    logo_url,
    org_type,
    website,
    location,
    about
) VALUES (
    $1, $2, $3, $4, $5, $6
)RETURNING firm_id, name, logo_url, org_type, website, location, about
`

type AddFirmParams struct {
	Name     string `json:"name"`
	LogoUrl  string `json:"logo_url"`
	OrgType  string `json:"org_type"`
	Website  string `json:"website"`
	Location string `json:"location"`
	About    string `json:"about"`
}

func (q *Queries) AddFirm(ctx context.Context, arg AddFirmParams) (Firm, error) {
	row := q.db.QueryRow(ctx, addFirm,
		arg.Name,
		arg.LogoUrl,
		arg.OrgType,
		arg.Website,
		arg.Location,
		arg.About,
	)
	var i Firm
	err := row.Scan(
		&i.FirmID,
		&i.Name,
		&i.LogoUrl,
		&i.OrgType,
		&i.Website,
		&i.Location,
		&i.About,
	)
	return i, err
}

const getFirm = `-- name: GetFirm :one
SELECT firm_id, name, logo_url, org_type, website, location, about FROM firms
WHERE firm_id = $1
`

func (q *Queries) GetFirm(ctx context.Context, firmID int64) (Firm, error) {
	row := q.db.QueryRow(ctx, getFirm, firmID)
	var i Firm
	err := row.Scan(
		&i.FirmID,
		&i.Name,
		&i.LogoUrl,
		&i.OrgType,
		&i.Website,
		&i.Location,
		&i.About,
	)
	return i, err
}

const listFirms = `-- name: ListFirms :many
SELECT firm_id, name, logo_url, org_type, website, location, about FROM firms
WHERE $3::text = '' OR name ILIKE '%' || $3 || '%'
ORDER BY firm_id
LIMIT $1
OFFSET $2
`

type ListFirmsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Query  string `json:"query"`
}

func (q *Queries) ListFirms(ctx context.Context, arg ListFirmsParams) ([]Firm, error) {
	rows, err := q.db.Query(ctx, listFirms, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Firm{}
	for rows.Next() {
		var i Firm
		if err := rows.Scan(
			&i.FirmID,
			&i.Name,
			&i.LogoUrl,
			&i.OrgType,
			&i.Website,
			&i.Location,
			&i.About,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
