// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: license.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveLicense = `-- name: SaveLicense :one
INSERT INTO licenses (
    user_id,
    name,
    license_number,
    issue_date,
    issue_state
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING license_id, user_id, name, license_number, issue_date, issue_state, license_url
`

type SaveLicenseParams struct {
	UserID        string      `json:"user_id"`
	Name          string      `json:"name"`
	LicenseNumber string      `json:"license_number"`
	IssueDate     pgtype.Date `json:"issue_date"`
	IssueState    string      `json:"issue_state"`
}

func (q *Queries) SaveLicense(ctx context.Context, arg SaveLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, saveLicense,
		arg.UserID,
		arg.Name,
		arg.LicenseNumber,
		arg.IssueDate,
		arg.IssueState,
	)
	var i License
	err := row.Scan(
		&i.LicenseID,
		&i.UserID,
		&i.Name,
		&i.LicenseNumber,
		&i.IssueDate,
		&i.IssueState,
		&i.LicenseUrl,
	)
	return i, err
}

const uploadLicense = `-- name: UploadLicense :one
UPDATE licenses
SET
    license_url = $1
WHERE
    user_id = $2
RETURNING license_id, user_id, name, license_number, issue_date, issue_state, license_url
`

type UploadLicenseParams struct {
	LicenseUrl *string `json:"license_url"`
	UserID     string  `json:"user_id"`
}

func (q *Queries) UploadLicense(ctx context.Context, arg UploadLicenseParams) (License, error) {
	row := q.db.QueryRow(ctx, uploadLicense, arg.LicenseUrl, arg.UserID)
	var i License
	err := row.Scan(
		&i.LicenseID,
		&i.UserID,
		&i.Name,
		&i.LicenseNumber,
		&i.IssueDate,
		&i.IssueState,
		&i.LicenseUrl,
	)
	return i, err
}
