// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Profile struct {
	ID       int64  `json:"id"`
	UserID   string `json:"user_id"`
	Headline string `json:"headline"`
	Summary  string `json:"summary"`
	Industry string `json:"industry"`
	Website  string `json:"website"`
}

type User struct {
	ID              string    `json:"id"`
	Email           string    `json:"email"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	IsEmailVerified bool      `json:"is_email_verified"`
	SignUpMethod    int32     `json:"sign_up_method"`
	JoinDate        time.Time `json:"join_date"`
}
