// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Experience struct {
	ExperienceID     int64  `json:"experience_id"`
	UserID           string `json:"user_id"`
	PracticeArea     string `json:"practice_area"`
	PracticeLocation string `json:"practice_location"`
	Experience       string `json:"experience"`
}

type License struct {
	LicenseID     int64   `json:"license_id"`
	UserID        string  `json:"user_id"`
	Name          string  `json:"name"`
	LicenseNumber string  `json:"license_number"`
	IssueDate     string  `json:"issue_date"`
	IssueState    string  `json:"issue_state"`
	LicensePdf    *string `json:"license_pdf"`
}

type User struct {
	UserID          string    `json:"user_id"`
	Email           string    `json:"email"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	Mobile          *string   `json:"mobile"`
	Address         *string   `json:"address"`
	ImageUrl        *string   `json:"image_url"`
	EmailVerified   bool      `json:"email_verified"`
	MobileVerified  bool      `json:"mobile_verified"`
	WizardStep      int32     `json:"wizard_step"`
	WizardCompleted bool      `json:"wizard_completed"`
	SignupMethod    int32     `json:"signup_method"`
	JoinDate        time.Time `json:"join_date"`
}
