// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: poll.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (
    owner_id,
    title,
    options,
    end_time
) VALUES (
    $1, $2, $3, $4
) RETURNING poll_id, owner_id, title, options, created_at, end_time
`

type CreatePollParams struct {
	OwnerID string             `json:"owner_id"`
	Title   string             `json:"title"`
	Options []string           `json:"options"`
	EndTime pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.OwnerID,
		arg.Title,
		arg.Options,
		arg.EndTime,
	)
	var i Poll
	err := row.Scan(
		&i.PollID,
		&i.OwnerID,
		&i.Title,
		&i.Options,
		&i.CreatedAt,
		&i.EndTime,
	)
	return i, err
}
