// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOTP(ctx context.Context, sessionID int64) error
	GetOTP(ctx context.Context, sessionID int64) (Otp, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id string) (User, error)
	SaveLicense(ctx context.Context, arg SaveLicenseParams) (License, error)
	StoreOTP(ctx context.Context, arg StoreOTPParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
