// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reviews.sql

package db

import (
	"context"
)

const addReview = `-- name: AddReview :one
INSERT INTO reviews (
    user_id,
    reviewer_id,
    review,
    rating
) VALUES (
   $1, $2, $3, $4
) RETURNING review_id, user_id, reviewer_id, review, rating, timestamp
`

type AddReviewParams struct {
	UserID     string `json:"user_id"`
	ReviewerID string `json:"reviewer_id"`
	Review     string `json:"review"`
	Rating     int32  `json:"rating"`
}

func (q *Queries) AddReview(ctx context.Context, arg AddReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, addReview,
		arg.UserID,
		arg.ReviewerID,
		arg.Review,
		arg.Rating,
	)
	var i Review
	err := row.Scan(
		&i.ReviewID,
		&i.UserID,
		&i.ReviewerID,
		&i.Review,
		&i.Rating,
		&i.Timestamp,
	)
	return i, err
}
