// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: social.sql

package db

import (
	"context"
)

const addSocial = `-- name: AddSocial :one
INSERT INTO socials (
    user_id,
    platform_name,
    link_url
) VALUES (
    $1, $2, $3
) RETURNING social_id, user_id, platform_name, link_url
`

type AddSocialParams struct {
	UserID       string `json:"user_id"`
	PlatformName string `json:"platform_name"`
	LinkUrl      string `json:"link_url"`
}

func (q *Queries) AddSocial(ctx context.Context, arg AddSocialParams) (Social, error) {
	row := q.db.QueryRow(ctx, addSocial, arg.UserID, arg.PlatformName, arg.LinkUrl)
	var i Social
	err := row.Scan(
		&i.SocialID,
		&i.UserID,
		&i.PlatformName,
		&i.LinkUrl,
	)
	return i, err
}
