// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: social.sql

package db

import (
	"context"
)

const addSocial = `-- name: AddSocial :one
INSERT INTO socials (
    entity_id,
    entity_type,
    platform,
    link
) VALUES (
    $1, $2, $3, $4
) RETURNING social_id, entity_id, entity_type, platform, link
`

type AddSocialParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Platform   string `json:"platform"`
	Link       string `json:"link"`
}

func (q *Queries) AddSocial(ctx context.Context, arg AddSocialParams) (Social, error) {
	row := q.db.QueryRow(ctx, addSocial,
		arg.EntityID,
		arg.EntityType,
		arg.Platform,
		arg.Link,
	)
	var i Social
	err := row.Scan(
		&i.SocialID,
		&i.EntityID,
		&i.EntityType,
		&i.Platform,
		&i.Link,
	)
	return i, err
}
