// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Faq struct {
	ID       int    `json:"id"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type Mutation struct {
}

type NewFaq struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type Query struct {
}
